name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/deploy-backend.yml'

concurrency:
  group: deploy-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          test -n "${{ secrets.DEPLOY_SSH_KEY }}" || { echo "Missing DEPLOY_SSH_KEY under *Secrets*"; exit 1; }
          test -n "${{ secrets.DEPLOY_HOST }}" || { echo "Missing DEPLOY_HOST under *Secrets*"; exit 1; }
          test -n "${{ secrets.DEPLOY_USER }}" || { echo "Missing DEPLOY_USER under *Secrets*"; exit 1; }

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
          log-public-key: true

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts

      # Use a user-owned directory (no sudo)
      - name: Ensure target directory exists
        run: |
          DEPLOY_PATH="${{ secrets.DEPLOY_PATH }}"
          if [ -z "$DEPLOY_PATH" ]; then DEPLOY_PATH="~/apps/smarthome/server"; fi
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "mkdir -p $DEPLOY_PATH"

      - name: Sync backend files
        run: |
          DEPLOY_PATH="${{ secrets.DEPLOY_PATH }}"
          if [ -z "$DEPLOY_PATH" ]; then DEPLOY_PATH="~/apps/smarthome/server"; fi
          rsync -az --delete \
            --exclude '.env' \
            --exclude 'node_modules' \
            --exclude '.git' \
            ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:$DEPLOY_PATH/
        # For a custom SSH port, add:  -e "ssh -p 2222"

      - name: Install deps, migrate, reload
        run: |
          DEPLOY_PATH="${{ secrets.DEPLOY_PATH }}"
          if [ -z "$DEPLOY_PATH" ]; then DEPLOY_PATH="~/apps/smarthome/server"; fi
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} <<EOF
            set -euo pipefail
            cd "$DEPLOY_PATH"

            # Ensure Node/npm exist
            command -v npm >/dev/null 2>&1 || { echo "npm not in PATH on remote host"; exit 1; }

            # Install production deps
            npm ci --omit=dev

            # Run migrations
            node scripts/migrate.js

            # Reload or start via pm2 (must be installed for this user)
            if command -v pm2 >/dev/null 2>&1; then
              pm2 reload smarthome-backend || pm2 start ecosystem.config.js --only smarthome-backend || true
              pm2 save || true
            else
              echo "pm2 not found; install with: npm i -g pm2"; exit 1
            fi
          EOF
